spring.application.name=agrofood_backend

# Database local
spring.datasource.url=jdbc:mariadb://localhost:3306/agrofood
spring.datasource.username=root
spring.datasource.password=pablo

# Base de datos en la nube
# spring.datasource.url=jdbc:mariadb://trolley.proxy.rlwy.net:17306/agrofood
# spring.datasource.username=root
# spring.datasource.password=BaoXEV7Y6v.4TgFQ1ac6gBSpGh_X.8iS

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.connection.charSet=utf8

# Naming strategy para que respete los nombres de tablas y columnas exactos
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.jackson.serialization.fail-on-empty-beans=false

# Server
server.port=8080